#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "flask"
name = "Flask Template"
description.en = "Application to install a Flask application"
description.fr = "Application permettant d'installer un site Flask"

version = "1.0~ynh2"

maintainers = ["Gildas-GH"]

[upstream]
license = "WTFPL"

[integration]
yunohost = ">= 11.2.5"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/app"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "Password that you will need to upload your code on YunoHost"
    help.fr = "Le mot de passe que vous utiliserez pour téléverser votre code sur YunoHost"
    type = "password"

    [install.db_type]
    help.en = "Choose the database to use"
    help.fr = "Choisissez la base de donnée à utiliser"
    type = "string"
    choices.postgresql = "PostgreSQL"
    choices.sqlite = "SQLite"
    choices.mariadb = "MariaDB"

[resources]
    [resources.system_user]
    allow_sftp = true
    allow_ssh = true
    home = "/home/yunohost.app/__APP__"

    [resources.install_dir]

    [resources.data_dir]
    dir = "/home/yunohost.app/__APP__"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3-dev, python3-pip, python3-venv"
